### ISSUE TITLE
previous objects being used / imported

### ISSUE THREAD

**Issue by mjardeli** [GoSecure/Cisco2Checkpoint#8]
Hi Martin,

Seems app is importing my previous attempts to produce config.

I tried to use an empty  file for 'customer_service_objects.xml' and 'customer_network_objects.xml', even without any object to import, it is loading my previous objects

# Number of hosts (imported from checkpoint xml): 62
# Number of subnet (imported from checkpoint xml): 24

Is there any temp file created? I am searching here on my system, but didnt find till now.

Do you have an idea which folder/objects I need to clean?

thanks,

**Comment by martindube** [comment]
Hi mjardeli,

Check `data/default_r7730_service_objects.xml`and `data/default_r7730_network_objects.xml`

**Comment by mjardeli** [comment]
Actually I spotted what is happening. Tested with this simple config:
object network object1
 host 1.1.1.1
object network object2
 host 1.1.1.2

it recognizes as two hosts imported from checkpoint xml
 Number of hosts (imported from checkpoint xml): 2

and is creating hosts with original object name instead of using the added prefix name I changed.
is it maybe a logic error ?
Is there a way to add prefix to those objects?

thanks for your help,

**Comment by martindube** [comment]
Now I remember why I didn't implemented a prefix addition to all objects. I have experienced several issues with duplicate objects (two objects with same IP, network or range). VPN suddently stopped working and I had even routing issues, both fixed by removing a duplicate object. Trust me, this should be avoided. 

Regarding the names prefix, the behavior is normal. It is only applied when an object is created "on the fly". For example, if a group is defined with an IP address that is not defined before, a new host will be created and the prefix will be H_ (by default).

**Comment by mjardeli** [comment]
Do you mean this error on check point? Never saw this before, maybe automatic nat configured. 

My problem is two objects with exact same object name but with different IP or network address. Currently if this happens, it will use the first object added. 
Maybe as suggestion for the future add on the logic check object name and IP/network address. 
I will find an alternative way, thanks again !
cheers

**Comment by mjardeli** [comment]
Solved, thanks.
